- name: "Upgrade all packages to the latest version"
  apt:
    update_cache: yes
    upgrade: yes

- name: "Install common packages"
  apt: name={{item}} state=present
  with_items:
       - python-apt
       - mailutils
       - curl
       - dnsutils
       - telnet
       - unzip
       - parted
       - mc
       - bc
       - golang
       - python-docker
       - python-pip
       - htop
       - mysql-client
       - tree
       - rsync

- name: "Create partition on the {{ data_volume_device }}"
  parted:     
    device: "{{ data_volume_device }}"
    number: 1
    state: present

- name: "Create {{ data_volume_mount_path }} directory"
  file:
    path: "{{ data_volume_mount_path }}"
    state: directory
    mode: 0755
    recurse: yes

- name: "Create a ext4 filesystem on the {{ data_volume_partition }}"
  filesystem:
    fstype: ext4
    dev: "{{ data_volume_partition }}"

- name: "Mount data-volume {{ data_volume_partition }} to the {{ data_volume_mount_path }}"
  mount:
    path: "{{ data_volume_mount_path }}"
    src: "{{ data_volume_partition }}"
    state: mounted
    fstype: ext4

- name: "Create partition on the {{ backups_volume_device }}"
  parted:
    device: "{{ backups_volume_device }}"
    number: 1
    state: present

- name: "Create {{ backups_volume_mount_path }} directory"
  file:
    path: "{{ backups_volume_mount_path }}"
    state: directory
    mode: 0755
    recurse: yes

- name: "Create a ext4 filesystem on the {{ backups_volume_partition }}"
  filesystem:
    fstype: ext4
    dev: "{{ backups_volume_partition }}"

- name: "Mount backups-volume {{ backups_volume_partition }} to the {{ backups_volume_mount_path }}"
  mount:
    path: "{{ backups_volume_mount_path }}"
    src: "{{ backups_volume_partition }}"
    state: mounted
    fstype: ext4

- name: "Set hostname"
  hostname:
    name: "{{ set_hostname }}"

- name: "Add hostname to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost {{ set_hostname }} {{ inventory_hostname }}"
    state: present

- name: "Update /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg"
  lineinfile:
    dest: /etc/cloud/cloud.cfg.d/01_debian_cloud.cfg
    regexp: '^manage_etc_hosts: true'
    line: "manage_etc_hosts: false"
    state: present

- name: "Set timezone to Europe/Kiev"
  timezone:
    name: Europe/Kiev

- name: "Change root mailbox"
  lineinfile:
    dest: /etc/aliases
    regexp: '^root: '
    line: "root: {{ notify_email }}"
    state: present
 
- name: "Update mail aliases"
  shell:
    newaliases

- name: "Add the 'setevoy' system user"
  user:
    name: "setevoy"
    shell: "/bin/bash"
    append: yes
    groups: "sudo"

- name: "Copy .vimrc to the 'root' user"
  copy:
    src: "files/vimrc"
    dest: "/root/.vimrc"

- name: "Copy .vimrc to the 'setevoy' user"
  copy:
    src: "files/vimrc"
    dest: "/home/setevoy/.vimrc"
